apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}--database
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}--database
    spec:
      containers:
        - name: {{ .Release.Name }}--database
          image: {{ .Values.repo.image}}:{{ .Values.repo.tag}}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.database.rootPassword }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.database.name }}"
            - name: MYSQL_USER
              value: "{{ .Values.database.user }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.database.password }}"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: backup-pvc

