{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
{{- end }}