apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  install_and_connect.sh: |
    #!/bin/bash
    apt-get update && apt-get install -y redis-tools
    if redis-cli -h "${REDIS_HOST}" -p "${REDIS_PORT}" -a "${REDIS_PASSWORD}" PING; then
        echo "Redis connection successful!"
    else
        echo "Redis connection failed!"
        exit 1
    fi
    tail -f /dev/null


    

