apiVersion: v2
name: umbrela
description: A Helm chart for Kubernetes
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: mysql
    version: 12.1.0
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 16.2.3
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    version: 16.3.1
    repository: https://charts.bitnami.com/bitnami

