apiVersion: v2
name: webapp
description: A Helm chart for a web application with optional Redis integration.
type: application
version: 0.1.0
dependencies:
  - name: redis
    version: 20.3.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled 
